make posix and add local option

diff --git a/backup_files b/backup_files
--- a/backup_files
+++ b/backup_files
@@ -8,10 +8,10 @@
 #******** USER VARIABLES ********#
 
 # Do Monthly backups:
-DO_DOM=1
+DO_DOM=${DO_DOM:-0}
 # Do Weekly incremental backups:
-DO_DOW=1
-SCRIPTDIR=/var/tmp/backup_info
+DO_DOW=${DO_DOW:-0}
+SCRIPTDIR=${SCRIPTDIR:-/var/tmp/backup_info}
 BDFILENAME=full-date
 FULLNAME=full
 INCRNAME=incr
@@ -29,10 +29,11 @@ BACKUPDIR=
 BACKUPTYPE=ssh
 BACKUPDOW="Mon"
 BACKUPENCPW=
+COMPRESSOPT=
+BACKUPEXT=tar
 
 #******** FUNCTIONS ********#
-function usage ()
-{
+usage() {
 	echo "Usage:"
 	echo "$0 [options]"
 	echo ""
@@ -40,18 +41,21 @@ function usage ()
 	echo ""
 	echo "Required options:"
 	echo "  -d <>. . . Directory list, space separated, abs path"
+	echo "  -p <>. . . Directory to put the backups on the destination"
+	echo "             (local=<dir>)"
+	echo "Required options for remote services:"
 	echo "  -o <>. . . Destination Host or service"
 	echo "             (ssh=<host>, smb=<host>/<share>)"
-	echo "  -p <>. . . Directory to put the backups on the remote server"
 	echo ""
 	echo "Type, file, authentication, encryption:"
 	echo "  -c <>. . . Credentials for backup type, default: 'backup'"
 	echo "             (ssh=<username>, smb=username:<smbuseropt>)"
 	echo "  -n <>. . . Name of file prefix, default: 'file_backup'"
 	echo "  -t <>. . . Type of backup, default: ssh"
-	echo "             (ssh, smb)"
+	echo "             (ssh, smb, local)"
 	echo "  -e <>. . . GPG encrypt file with given password"
-	echo "             (currently only supported via ssh)"
+	echo "             (Currently only supported via ssh)"
+	echo "  -z <>. . . Compress tar option, default: 'z'"
 	echo ""
 	echo "Schedule (as output by date %a,%d):"
 	echo "  -m <>. . . Day of month to do monthly full backup, default: 01"
@@ -69,7 +73,7 @@ function usage ()
 	echo ""
 }
 
-function log_it () {
+log_it() {
 
 	#logger -t "$(basename -- $0)" -s -i -- $1
 	#logger -t "$(basename -- $0)" -i -- $1
@@ -79,16 +83,16 @@ function log_it () {
 	echo $1 >> $LOGNAME 2>&1
 }
 
-function ssh_type () {
+ssh_type() {
 
 	######### REMOVE THE OLD WORKING
 
 	log_it "running: rm old working"
-	ssh -l ${BACKUPUSER} -- ${BACKUPHOST} rm -f $BACKUPDIR/$BACKUPNAME-$TYPENAME.tgz.working >> $LOGNAME 2>&1
+	ssh -l ${BACKUPUSER} -- ${BACKUPHOST} rm -f $BACKUPDIR/$BACKUPNAME-$TYPENAME.$BACKUPEXT.working >> $LOGNAME 2>&1
 	log_it "executed: rm old working"
 
 	#~~~~~~~~~ KLUDGE UNTIL MORE DISK SPACE, REMOVE THE OLD BACKUP TOO
-	#ssh -l ${BACKUPUSER} -- ${BACKUPHOST} rm -f $BACKUPDIR/$BACKUPNAME-$TYPENAME.tgz >> $LOGNAME 2>&1
+	#ssh -l ${BACKUPUSER} -- ${BACKUPHOST} rm -f $BACKUPDIR/$BACKUPNAME-$TYPENAME.$BACKUPEXT >> $LOGNAME 2>&1
 	#log_it "executed: rm orig"
 	#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
@@ -96,15 +100,15 @@ function ssh_type () {
 
 	log_it "running: tar with $NEWER and $FROMDATE on $DIRECTORIES"
 	RET=1
-        # TODO putting an empty "$FROMDATE" will cause one harmless "tar: : No such file or directory" message
-	nice tar $NEWER "$FROMDATE" -czf - $DIRECTORIES 2>> $LOGNAME | ssh -l ${BACKUPUSER} -- ${BACKUPHOST} "( cat > $BACKUPDIR/$BACKUPNAME-$TYPENAME.tgz.working )" >> $LOGNAME 2>&1
+	# TODO putting an empty "$FROMDATE" will cause one harmless "tar: : No such file or directory" message
+	nice tar $NEWER "$FROMDATE" -c $COMPRESSOPT -f - $DIRECTORIES 2>> $LOGNAME | ssh -l ${BACKUPUSER} -- ${BACKUPHOST} "( cat > $BACKUPDIR/$BACKUPNAME-$TYPENAME.$BACKUPEXT.working )" >> $LOGNAME 2>&1
 	RET="$?"
 	log_it "executed: tar with RET=$RET"
 
 	######### MOVE TO KEEP IF EVERYTHING WENT GOOD
 
-	if [[ "$RET" == "0" ]]; then
-		ssh -l ${BACKUPUSER} -- ${BACKUPHOST} mv -f $BACKUPDIR/$BACKUPNAME-$TYPENAME.tgz.working $BACKUPDIR/$BACKUPNAME-$TYPENAME.tgz >> $LOGNAME 2>&1
+	if [ "$RET" = "0" ]; then
+		ssh -l ${BACKUPUSER} -- ${BACKUPHOST} mv -f $BACKUPDIR/$BACKUPNAME-$TYPENAME.$BACKUPEXT.working $BACKUPDIR/$BACKUPNAME-$TYPENAME.$BACKUPEXT >> $LOGNAME 2>&1
 		echo "$BD" > "$ADDTOBDFILENAME" #this only adds if not dev null
 		log_it "executed: mv working to main for $BD in $ADDTOBDFILENAME"
 
@@ -112,17 +116,17 @@ function ssh_type () {
 		if [ ! -z "$BACKUPENCPW" ]; then
 			log_it "gpg encrypting"
 			# Encrypt if requested
-			ssh -l ${BACKUPUSER} -- ${BACKUPHOST} gpg --yes --batch --no-use-agent --passphrase=$BACKUPENCPW -c $BACKUPDIR/$BACKUPNAME-$TYPENAME.tgz >> $LOGNAME 2>&1
+			ssh -l ${BACKUPUSER} -- ${BACKUPHOST} gpg --yes --batch --no-use-agent --passphrase=$BACKUPENCPW -c $BACKUPDIR/$BACKUPNAME-$TYPENAME.$BACKUPEXT >> $LOGNAME 2>&1
 			RET="$?"
-			if [[ "$RET" == "0" ]]; then
-				ssh -l ${BACKUPUSER} -- ${BACKUPHOST} rm -f $BACKUPDIR/$BACKUPNAME-$TYPENAME.tgz >> $LOGNAME 2>&1
+			if [ "$RET" = "0" ]; then
+				ssh -l ${BACKUPUSER} -- ${BACKUPHOST} rm -f $BACKUPDIR/$BACKUPNAME-$TYPENAME.$BACKUPEXT >> $LOGNAME 2>&1
 			fi
 			log_it "encrypted"
 		fi
 	fi
 }
 
-function smb_type () {
+smb_type() {
 
 	TMPMOUNTPOINT=/mnt
 
@@ -134,11 +138,11 @@ function smb_type () {
 
 		######### REMOVE THE OLD WORKING
 
-		rm -f $TMPMOUNTPOINT/$BACKUPDIR/$BACKUPNAME-$TYPENAME.tgz.working >> $LOGNAME 2>&1
+		rm -f $TMPMOUNTPOINT/$BACKUPDIR/$BACKUPNAME-$TYPENAME.$BACKUPEXT.working >> $LOGNAME 2>&1
 		log_it "executed: rm old working"
 
 		#~~~~~~~~~ KLUDGE UNTIL MORE DISK SPACE, REMOVE THE OLD BACKUP TOO
-		#rm -f $TMPMOUNTPOINT/$BACKUPDIR/$BACKUPNAME-$TYPENAME.tgz >> $LOGNAME 2>&1
+		#rm -f $TMPMOUNTPOINT/$BACKUPDIR/$BACKUPNAME-$TYPENAME.$BACKUPEXT >> $LOGNAME 2>&1
 		#log_it "executed: rm orig"
 		#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
@@ -146,14 +150,14 @@ function smb_type () {
 
 		log_it "running: tar with $NEWER and $FROMDATE on $DIRECTORIES"
 		RET=1
-		nice tar $NEWER "$FROMDATE" -czf ${TMPMOUNTPOINT}/$BACKUPDIR/$BACKUPNAME-$TYPENAME.tgz.working $DIRECTORIES >> $LOGNAME 2>&1
+		nice tar $NEWER "$FROMDATE" -c $COMPRESSOPT -f ${TMPMOUNTPOINT}/$BACKUPDIR/$BACKUPNAME-$TYPENAME.$BACKUPEXT.working $DIRECTORIES >> $LOGNAME 2>&1
 		RET="$?"
 		log_it "executed: tar with RET=$RET"
 
 		######### MOVE TO KEEP IF EVERYTHING WENT GOOD
 
 		if [ "$RET" = "0" ]; then
-			mv -f $TMPMOUNTPOINT/$BACKUPDIR/$BACKUPNAME-$TYPENAME.tgz.working $TMPMOUNTPOINT/$BACKUPDIR/$BACKUPNAME-$TYPENAME.tgz >> $LOGNAME 2>&1
+			mv -f $TMPMOUNTPOINT/$BACKUPDIR/$BACKUPNAME-$TYPENAME.$BACKUPEXT.working $TMPMOUNTPOINT/$BACKUPDIR/$BACKUPNAME-$TYPENAME.$BACKUPEXT >> $LOGNAME 2>&1
 			echo "$BD" > "$ADDTOBDFILENAME" #this only adds if not dev null
 			log_it "executed: mv working to main"
 		fi
@@ -163,13 +167,42 @@ function smb_type () {
 	fi
 }
 
+local_type() {
+
+	######### REMOVE THE OLD WORKING
+
+	rm -f $BACKUPDIR/$BACKUPNAME-$TYPENAME.$BACKUPEXT.working >> $LOGNAME 2>&1
+	log_it "executed: rm old working"
+
+	#~~~~~~~~~ KLUDGE UNTIL MORE DISK SPACE, REMOVE THE OLD BACKUP TOO
+	#rm -f $BACKUPDIR/$BACKUPNAME-$TYPENAME.$BACKUPEXT >> $LOGNAME 2>&1
+	#log_it "executed: rm orig"
+	#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+
+	######### TAR IT UP
+
+	log_it "running: tar with $NEWER and $FROMDATE on $DIRECTORIES"
+	RET=1
+	nice tar $NEWER "$FROMDATE" -c $COMPRESSOPT -f $BACKUPDIR/$BACKUPNAME-$TYPENAME.$BACKUPEXT.working $DIRECTORIES >> $LOGNAME 2>&1
+	RET="$?"
+	log_it "executed: tar with RET=$RET"
+
+	######### MOVE TO KEEP IF EVERYTHING WENT GOOD
+
+	if [ "$RET" = "0" ]; then
+		mv -f $BACKUPDIR/$BACKUPNAME-$TYPENAME.$BACKUPEXT.working $BACKUPDIR/$BACKUPNAME-$TYPENAME.$BACKUPEXT >> $LOGNAME 2>&1
+		echo "$BD" > "$ADDTOBDFILENAME" #this only adds if not dev null
+		log_it "executed: mv working to main"
+	fi
+}
+
 #******** MAIN ********#
 
 PATH=/usr/local/bin:/usr/bin:/bin:$PATH
 
 ######### PARSE AND CHECK REQUIRED ARGS
 
-while getopts "c:d:e:fim:n:o:p:t:w:" flag; do
+while getopts "c:d:e:fim:n:o:p:t:w:z:" flag; do
 	case $flag in
 		[c])
 			BACKUPUSER="$OPTARG"
@@ -204,6 +237,9 @@ while getopts "c:d:e:fim:n:o:p:t:w:" flag; do
 		[w])
 			BACKUPDOW="$OPTARG"
 			;;
+		[z])
+			COMPRESSOPT=-"$OPTARG"
+			;;
 		*)
 			echo "Unexpected Argument"
 			usage
@@ -212,8 +248,13 @@ while getopts "c:d:e:fim:n:o:p:t:w:" flag; do
 	esac
 done
 
-if [ -z "$BACKUPHOST" -o -z "$DIRECTORIES" -o -z "$BACKUPDIR" ]; then
-	echo "Required arguments not found"
+if [ -z "$DIRECTORIES" ] || [ -z "$BACKUPDIR" ]; then
+	echo "Required arguments not found DIRECTORIES=$DIRECTORIES BACKUPDIR=$BACKUPDIR"
+	usage
+	exit 1
+fi
+if [ "$BACKUPTYPE" != "local" ] && [ -z "$BACKUPHOST" ]; then
+	echo "Required arguments not found BACKUPTYPE=$BACKUPTYPE BACKUPHOST=$BACKUPHOST"
 	usage
 	exit 1
 fi
@@ -228,6 +269,9 @@ ADDTOBDFILENAME="/dev/null"
 DOW=`date +%a` # Day of the week e.g. Mon
 DOM=`date +%d` # Date of the Month e.g. 27
 BD="$(date '+%Y-%m-%d %H:%M:%S')" #Date in day-Month format for the date file and tar newer
+if [ "$COMPRESSOPT" = "-z" ]; then
+	BACKUPEXT=tgz
+fi
 
 ######### CREATE THE BACKUP INFO DIR
 
@@ -240,18 +284,18 @@ log_it "$(date) STARTING $0"
 ######### FIGURE OUT WHAT TYPE OF BACKUP
 
 # if $FORCEFULL or its the first of the month, do this kind.  Flag must be set above.
-if ([ "$DOM" = "$BACKUPDOM" ] || [ "$FORCEFULL" = "1" ]) && [ "$DO_DOM" = "1" ]; then
+if ( [ "$DOM" = "$BACKUPDOM" ] && [ "$DO_DOM" = "1" ] ) || [ "$FORCEFULL" = "1" ]; then
 	# THIS IS THE FULL BACKUP
 	TYPENAME=$FULLNAME
 	ADDTOBDFILENAME="$SCRIPTDIR/$BACKUPNAME-$BDFILENAME"
 	FROMDATE=
 
 # if $FORCEINCR or its a monday, do this kind.  Flag must be set above.
-elif ([ $DOW = "$BACKUPDOW" ] || [ "$FORCEINCR" = "1" ]) && [ "$DO_DOW" = "1" ]; then
+elif ( [ $DOW = "$BACKUPDOW" ] && [ "$DO_DOW" = "1" ] ) || [ "$FORCEINCR" = "1" ]; then
 	# THIS IS THE INCREMENTAL BACKUP
 	TYPENAME=$INCRNAME
 	TEMPFROMDATE="$(cat $SCRIPTDIR/$BACKUPNAME-$BDFILENAME)"
-	if [[ "$TEMPFROMDATE" != "" ]]; then
+	if [ "$TEMPFROMDATE" != "" ]; then
 		FROMDATE="$TEMPFROMDATE"
 		NEWER="--newer"
 	fi
@@ -259,7 +303,7 @@ fi
 
 ######### EXIT IF WE ARENT DOING A BACKUP TODAY
 
-if [[ "$TYPENAME" == "" ]]; then
+if [ "$TYPENAME" = "" ]; then
 	log_it "Backup ran with no TYPENAME, exiting."
 	exit 0
 fi
@@ -267,7 +311,7 @@ fi
 ######### START THE BACKUP
 
 log_it "#########################"
-log_it "Running for BACKUPUSER=${BACKUPUSER} BACKUPHOST=${BACKUPHOST} BACKUPDIR=${BACKUPDIR} BACKUPNAME=${BACKUPNAME} TYPENAME=${TYPENAME} BACKUPTYPE=${BACKUPTYPE} BACKUPDOM=${BACKUPDOM} BACKUPDOW=${BACKUPDOW}"
+log_it "Running for BACKUPUSER=${BACKUPUSER} BACKUPHOST=${BACKUPHOST} BACKUPDIR=${BACKUPDIR} BACKUPNAME=${BACKUPNAME} TYPENAME=${TYPENAME} BACKUPTYPE=${BACKUPTYPE} BACKUPDOM=${BACKUPDOM} BACKUPDOW=${BACKUPDOW} COMPRESSOPT=${COMPRESSOPT} BACKUPEXT=${BACKUPEXT}"
 
 if [ "$BACKUPTYPE" = "ssh" ]; then
 	ssh_type
@@ -275,6 +319,10 @@ fi
 
 if [ "$BACKUPTYPE" = "smb" ]; then
 	smb_type
+fi
+
+if [ "$BACKUPTYPE" = "local" ]; then
+	local_type
 fi
 
 ######### COMPLETE
